org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
android.enableJetifier=true

# Stabilizing R8 configuration
android.enableR8.fullMode=true
android.nonTransitiveRClass=false
android.nonFinalResIds=true
android.enableResourceOptimizations=false

RELEASE_STORE_FILE=hoshiyaar.jks
RELEASE_STORE_PASSWORD=hoshiyaar123
RELEASE_KEY_ALIAS=hoshiyaar-key
RELEASE_KEY_PASSWORD=hoshiyaar123
